src/components/atoms/Link/Link.tsx

[add]src\components\atoms\Linkの追加

---

src/components/atoms/Text/Text.tsx

update: コンポーネント名の変更

---

src/components/template/SignupForm/SignupForm.tsx
src/index.tsx
src/pages/Signup/Signup.tsx

src\components\template\SignupForm、src\pages\Signupの追加、及びそれに該当するindex.tsx #17, 18の追加

[add]サインアップに関する画面の追加

---

src/types/postType.ts

update: 型の更新

---

src/pages/Signup/Signup.tsx

サインアップ処理の追加
ログイン状態の確認をカスタムフック呼び出しに変更

update: サインアップ処理追加など

---

src/components/organisms/Post/Post.tsx

add: 投稿のひな形

---

src/components/organisms/Footer/Footer.tsx
src/components/organisms/Header/Header.tsx
src/index.css

organisms\Footer\Footer・organisms\Header\Headerの追加、index.css #3~#7の追加

[add]ヘッダー、フッターコンポーネントの追加、及びそれに関するindex.cssの編集

---

src/hooks/useUserData.tsx

add: DBからユーザーのデータを取得するカスタムフック

---

src/components/template/Default/Default.tsx
src/pages/Login/Login.tsx
src/pages/NotFound/NotFound.tsx
src/pages/Signup/Signup.tsx
src/pages/Top/Top.tsx

components\template\Default\Defaultの追加、それに伴うpages内全ソースへのDefaultの追記

[up]全ページに適用されるDefaultの追加

---

src/index.tsx
src/pages/TagList/TagList.tsx

src\pages\TagList.tsxを新規作成し、src\index.tsx #21 を追加しました

[add]タグ一覧ページの追加、及びルーティング"/tags"の設定

---

src/components/organisms/BreadCrumbs/BreadCrumbs.tsx
src/components/organisms/Header/Header.tsx
src/components/template/Default/Default.tsx
src/pages/TagList/TagList.tsx

BreadCrumb.tsxを追加し、Default.tsx、TagList.tsxを変更しました。尚、Headerはhoverを追加しました。

[add]パンくずリストの追加、及びそれに伴うDefaultの変更

---

src/index.tsx
src/pages/TagList/TagList.tsx

TagList.tsx #38 "tags/~~"を"tags?tag=~~"に変更し、index.tsx #21のURLを変更しました

[fix]タグ一覧ページでの画面遷移をgetに変更し、URLをtagsに変更

---

src/components/organisms/Post/Post.tsx

アイコンを左に置いて右側にユーザー名とメッセージを表示するように変更

update: レイアウトの変更

---

src/utils/getFollow.ts

ログインユーザーのフォロータグを一覧で返す処理をutilsに新規作成しました(とりあえずじかんなかったので処理だけ作ってます)

[add]getFollowの作成

---

src/components/organisms/FollowsForm/FollowsForm.tsx
src/pages/FollowTag/FollowTag.tsx

FollowsTag #22~38を追加し、それに伴ってFollowsFormへ引数を追加しました。

update: 推し一覧画面へonClick属性の追加

---

public/index.html
src/components/organisms/Header/Header.tsx

fix: 全体テンプレートの微修正

---

src/components/organisms/AddTagModalWindow/AddTagModalWindow.tsx

開閉を親から渡すように変更
タグの追加時に発火する関数を渡せるように変更
cssの切り出し

update: タグを追加するモーダルウィンドウの変更

---

src/pages/Follow/index.tsx

切り出し前のコードの削除
切り出し前のロジックを関数化して渡すように変更

update: フォロー/フォロー解除ボタンの切り出しに伴う修正

---

src/pages/Follow/index.tsx

fix: 文字以外の要素にLinkが設定されていた問題の修正

---

src/components/organisms/FollowButton/index.tsx

update: cssの変更

---

src/pages/Tags/Tag.tsx
src/pages/Tags/style.ts

add: タグ一覧画面のタグの部分

---

src/hooks/useFollowTags.tsx

フォロー中のタグ、取得関数、取得処理が走ったかのbool値、エラーを返す

add: フォロー中のタグを取得するhooks

---

src/hooks/useAllTags.tsx

Reverts ishida-0622/hack-u-2022#171

Revert "update: 変数名の変更、コメントの修正"

---

src/components/organisms/Header/index.tsx
src/pages/Signup/index.tsx
src/utils/addPost.ts

コメントの追加、スペルミスの修正、不要な空タグの削除、引数をreadonlyに変更

clean: コメントの追加、スペルミスの修正など

---

src/pages/Tags/ShowTag.tsx
src/pages/Tags/index.tsx

表示するタグをGETで管理していたものをstateで管理するように変更

update: 表示するタグをGETで管理していたものをstateで管理するように変更

---

src/index.css
src/pages/Top/index.tsx
src/pages/Top/style.ts

update: cssの変更、遷移先の変更など
